# Generated by Django 4.1.2 on 2022-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Offering', 'Offering'), ('Tithe', 'Tithe'), ('Thanksgiving', 'Thanksgiving'), ('Transport', 'Transport'), ('Project 22', 'Project 22'), ('Shiloh Sacrifice', 'Shiloh Sacrifice'), ('Welfare', 'Welfare'), ('Prophet Offering', 'Prophet Offering')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
    ]
