# Generated by Django 4.1.2 on 2022-10-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
