# Generated by Django 4.1.2 on 2022-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(default='aad@gm.co', max_length=254),
        ),
    ]
