# Generated by Django 4.1.2 on 2022-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cart_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
